import pytz

CONST_TIMEZONE = pytz.timezone("Asia/Saigon")
CONST_EKYC_REMINDER = "EKYC_REMINDER"
CONST_ITEM_REMINDER = "ITEM_REMINDER"
CONST_EKYC_DONE = "EKYC_DONE"
CONST_EKYC_BLOCK = "EKYC_BLOCK"
CONST_EKYC_FAIL = "EKYC_FAIL"
CONST_ITEM_EXPIRE = "ITEM_EXPIRE"
CONST_ITEM_WILL_EXPIRE = "ITEM_WILL_EXPIRE"
CONST_ITEM_REMINDER_D3 = "ITEM_REMINDER_D3"
CONST_REGISTER_COMPLETE = "REGISTER_COMPLETE"
CONST_DEFAULT = "DEFAULT"
CONST_PAYMENT_REMINDER_D_3 = "PAYMENT_REMINDER_D-3"
CONST_PAYMENT_REMINDER_D0 = "PAYMENT_REMINDER_D0"
CONST_PAYMENT_SUCCESS_START = "PAYMENT_SUCCESS_START"
CONST_PAYMENT_SUCCESS_END = "PAYMENT_SUCCESS_END"

